# Generated by Django 5.2.4 on 2025-08-01 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaCosteoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('costo', models.ForeignKey(help_text='Costo asociado a la oferta, utilizado para calcular el precio y detalles de venta', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_costo', to='costos.costosmodel', verbose_name='Costo')),
            ],
            options={
                'verbose_name': 'Oferta de Costeo',
                'verbose_name_plural': 'Ofertas de Costeo',
                'managed': True,
            },
        ),
    ]
