# Generated by Django 5.2.4 on 2025-07-29 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumnosInscritosModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_inscripcion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha en que el alumno se inscribió al curso",
                        verbose_name="Fecha de inscripción",
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        help_text="Usuario asociado al alumno",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario del alumno",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        help_text="Curso al que está inscrito el alumno",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_curso",
                        to="cursos.cursosmodel",
                        verbose_name="Curso del alumno",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_usuario_creacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_usuario_modificacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumno Inscrito",
                "verbose_name_plural": "Alumnos Inscritos",
                "managed": True,
                "unique_together": {("alumno", "curso")},
            },
        ),
    ]
