# Generated by Django 5.2.4 on 2025-08-01 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnosinscritosmodel',
            name='alumno',
            field=models.ForeignKey(help_text='Usuario asociado al alumno', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del alumno'),
        ),
        migrations.AddField(
            model_name='alumnosinscritosmodel',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumnosinscritosmodel',
            name='usuario_modificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_usuario_modificacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriasmodel',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriasmodel',
            name='usuario_modificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_usuario_modificacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cursosmodel',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_categoria', to='cursos.categoriasmodel', verbose_name='Categoría del curso'),
        ),
        migrations.AddField(
            model_name='cursosmodel',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cursosmodel',
            name='usuario_modificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_usuario_modificacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumnosinscritosmodel',
            name='curso',
            field=models.ForeignKey(help_text='Curso al que está inscrito el alumno', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_curso', to='cursos.cursosmodel', verbose_name='Curso del alumno'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnosinscritosmodel',
            unique_together={('alumno', 'curso')},
        ),
    ]
