# Generated by Django 5.2.4 on 2025-08-01 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorCosteoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('costo', models.ForeignKey(help_text='Costo asociado al patrocinador, utilizado para calcular el precio y detalles de patrocinio', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_costo', to='costos.costosmodel', verbose_name='Costo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_usuario_creacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_usuario_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patrocinador de Costeo',
                'verbose_name_plural': 'Patrocinadores de Costeo',
                'managed': True,
            },
        ),
    ]
