# Generated by Django 5.2.4 on 2025-07-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialPagos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
